
#ALY6030
#ASSIGNMENT 1 - SQL
#NYINAKU,ISAAC
#SEPTEMBER 21, 2025. 
###Creating a Schema to use###

-- Create database
CREATE DATABASE IF NOT EXISTS vaccinations;
USE vaccinations;
##############################################################################################################
-- Country table
CREATE TABLE country (
    country_id     INT (10) AUTO_INCREMENT,
    country_name   VARCHAR(100) NOT NULL,
    iso3           VARCHAR(3) NOT NULL UNIQUE,
    who_region     VARCHAR (5) NOT NULL,
    PRIMARY KEY (country_id)
);

#Checking country table created by using select statement
SELECT * FROM country;

#INSERTING DATA INTO country table
INSERT INTO country (country_name, iso3, who_region) VALUES
('Afghanistan', 'AFG', 'EMRO'),
('Albania', 'ALB', 'EURO'),
('Algeria', 'DZA', 'AFRO'),
('American Samoa', 'ASM', 'WPRO'),
('Andorra', 'AND', 'EURO'),
('Angola', 'AGO', 'AFRO'),
('Anguilla', 'AIA', 'AMRO'),
('Antigua and Barbuda', 'ATG', 'AMRO'),
('Argentina', 'ARG', 'AMRO'),
('Armenia', 'ARM', 'EURO'),
('Aruba', 'ABW', 'AMRO'),
('Australia', 'AUS', 'WPRO'),
('Austria', 'AUT', 'EURO'),
('Azerbaijan', 'AZE', 'EURO'),
('Bahamas', 'BHS', 'AMRO'),
('Bahrain', 'BHR', 'EMRO'),
('Bangladesh', 'BGD', 'SEARO'),
('Barbados', 'BRB', 'AMRO'),
('Belarus', 'BLR', 'EURO'),
('Belgium', 'BEL', 'EURO'),
('Belize', 'BLZ', 'AMRO'),
('Benin', 'BEN', 'AFRO'),
('Bermuda', 'BMU', 'AMRO'),
('Bhutan', 'BTN', 'SEARO'),
('Bolivia (Plurinational State of)', 'BOL', 'AMRO'),
('Bonaire', 'XAA', 'AMRO'),
('Bonaire, Sint Eustatius and Saba', 'BES', 'AMRO'),
('Bosnia and Herzegovina', 'BIH', 'EURO'),
('Botswana', 'BWA', 'AFRO'),
('Brazil', 'BRA', 'AMRO'),
('British Virgin Islands', 'VGB', 'AMRO'),
('Brunei Darussalam', 'BRN', 'WPRO'),
('Bulgaria', 'BGR', 'EURO'),
('Burkina Faso', 'BFA', 'AFRO'),
('Burundi', 'BDI', 'AFRO'),
('Cabo Verde', 'CPV', 'AFRO'),
('Cambodia', 'KHM', 'WPRO'),
('Cameroon', 'CMR', 'AFRO'),
('Canada', 'CAN', 'AMRO'),
('Cayman Islands', 'CYM', 'AMRO'),
('Central African Republic', 'CAF', 'AFRO'),
('Chad', 'TCD', 'AFRO'),
('Chile', 'CHL', 'AMRO'),
('China', 'CHN', 'WPRO'),
('Colombia', 'COL', 'AMRO'),
('Comoros', 'COM', 'AFRO'),
('Congo', 'COG', 'AFRO'),
('Cook Islands', 'COK', 'WPRO'),
('Costa Rica', 'CRI', 'AMRO'),
('Côte d’Ivoire', 'CIV', 'AFRO'),
('Croatia', 'HRV', 'EURO'),
('Cuba', 'CUB', 'AMRO'),
('Curaçao', 'CUW', 'AMRO'),
('Cyprus', 'CYP', 'EURO'),
('Czechia', 'CZE', 'EURO'),
('Democratic Republic of the Congo', 'COD', 'AFRO'),
('Denmark', 'DNK', 'EURO'),
('Djibouti', 'DJI', 'EMRO'),
('Dominica', 'DMA', 'AMRO'),
('Dominican Republic', 'DOM', 'AMRO'),
('Ecuador', 'ECU', 'AMRO'),
('Egypt', 'EGY', 'EMRO'),
('El Salvador', 'SLV', 'AMRO'),
('Equatorial Guinea', 'GNQ', 'AFRO'),
('Eritrea', 'ERI', 'AFRO'),
('Estonia', 'EST', 'EURO'),
('Eswatini', 'SWZ', 'AFRO'),
('Ethiopia', 'ETH', 'AFRO'),
('Falkland Islands (Malvinas)', 'FLK', 'AMRO'),
('Faroe Islands', 'FRO', 'EURO'),
('Fiji', 'FJI', 'WPRO'),
('Finland', 'FIN', 'EURO'),
('France', 'FRA', 'EURO'),
('French Guiana', 'GUF', 'AMRO'),
('French Polynesia', 'PYF', 'WPRO'),
('Gabon', 'GAB', 'AFRO'),
('Gambia', 'GMB', 'AFRO'),
('Georgia', 'GEO', 'EURO'),
('Germany', 'DEU', 'EURO'),
('Ghana', 'GHA', 'AFRO'),
('Gibraltar', 'GIB', 'EURO'),
('Greece', 'GRC', 'EURO'),
('Greenland', 'GRL', 'EURO'),
('Grenada', 'GRD', 'AMRO'),
('Guadeloupe', 'GLP', 'AMRO'),
('Guam', 'GUM', 'WPRO'),
('Guatemala', 'GTM', 'AMRO'),
('Guernsey', 'GGY', 'EURO'),
('Guinea', 'GIN', 'AFRO'),
('Guinea-Bissau', 'GNB', 'AFRO'),
('Guyana', 'GUY', 'AMRO'),
('Haiti', 'HTI', 'AMRO'),
('Honduras', 'HND', 'AMRO'),
('Hungary', 'HUN', 'EURO'),
('Iceland', 'ISL', 'EURO'),
('India', 'IND', 'SEARO'),
('Indonesia', 'IDN', 'SEARO'),
('Iran (Islamic Republic of)', 'IRN', 'EMRO'),
('Iraq', 'IRQ', 'EMRO'),
('Ireland', 'IRL', 'EURO'),
('Isle of Man', 'IMN', 'EURO'),
('Israel', 'ISR', 'EURO'),
('Italy', 'ITA', 'EURO'),
('Jamaica', 'JAM', 'AMRO'),
('Japan', 'JPN', 'WPRO'),
('Jersey', 'JEY', 'EURO'),
('Jordan', 'JOR', 'EMRO'),
('Kazakhstan', 'KAZ', 'EURO'),
('Kenya', 'KEN', 'AFRO'),
('Kiribati', 'KIR', 'WPRO'),
('Kosovo', 'XKX', 'EURO'),
('Kuwait', 'KWT', 'EMRO'),
('Kyrgyzstan', 'KGZ', 'EURO'),
('Lao People''s Democratic Republic', 'LAO', 'WPRO'),
('Latvia', 'LVA', 'EURO'),
('Lebanon', 'LBN', 'EMRO'),
('Lesotho', 'LSO', 'AFRO'),
('Liberia', 'LBR', 'AFRO'),
('Libya', 'LBY', 'EMRO'),
('Liechtenstein', 'LIE', 'OTHER'),
('Lithuania', 'LTU', 'EURO'),
('Luxembourg', 'LUX', 'EURO'),
('Madagascar', 'MDG', 'AFRO'),
('Malawi', 'MWI', 'AFRO'),
('Malaysia', 'MYS', 'WPRO'),
('Maldives', 'MDV', 'SEARO'),
('Mali', 'MLI', 'AFRO'),
('Malta', 'MLT', 'EURO'),
('Marshall Islands', 'MHL', 'WPRO'),
('Martinique', 'MTQ', 'AMRO'),
('Mauritania', 'MRT', 'AFRO'),
('Mauritius', 'MUS', 'AFRO'),
('Mexico', 'MEX', 'AMRO'),
('Micronesia (Federated States of)', 'FSM', 'WPRO'),
('Monaco', 'MCO', 'EURO'),
('Mongolia', 'MNG', 'WPRO'),
('Montenegro', 'MNE', 'EURO'),
('Montserrat', 'MSR', 'AMRO'),
('Morocco', 'MAR', 'EMRO'),
('Mozambique', 'MOZ', 'AFRO'),
('Myanmar', 'MMR', 'SEARO'),
('Namibia', 'NAM', 'AFRO'),
('Nauru', 'NRU', 'WPRO'),
('Nepal', 'NPL', 'SEARO'),
('Netherlands', 'NLD', 'EURO'),
('New Caledonia', 'NCL', 'WPRO'),
('New Zealand', 'NZL', 'WPRO'),
('Nicaragua', 'NIC', 'AMRO'),
('Niger', 'NER', 'AFRO'),
('Nigeria', 'NGA', 'AFRO'),
('Niue', 'NIU', 'WPRO'),
('North Macedonia', 'MKD', 'EURO'),
('Northern Mariana Islands (Commonwealth of the)', 'MNP', 'WPRO'),
('Norway', 'NOR', 'EURO'),
('occupied Palestinian territory', 'PSE', 'EMRO'),
('Oman', 'OMN', 'EMRO'),
('Pakistan', 'PAK', 'EMRO'),
('Palau', 'PLW', 'WPRO'),
('Panama', 'PAN', 'AMRO'),
('Papua New Guinea', 'PNG', 'WPRO'),
('Paraguay', 'PRY', 'AMRO'),
('Peru', 'PER', 'AMRO'),
('Philippines', 'PHL', 'WPRO'),
('Pitcairn Islands', 'PCN', 'WPRO'),
('Poland', 'POL', 'EURO'),
('Portugal', 'PRT', 'EURO'),
('Puerto Rico', 'PRI', 'AMRO'),
('Qatar', 'QAT', 'EMRO'),
('Republic of Korea', 'KOR', 'WPRO'),
('Republic of Moldova', 'MDA', 'EURO'),
('Romania', 'ROU', 'EURO'),
('Russian Federation', 'RUS', 'EURO'),
('Rwanda', 'RWA', 'AFRO'),
('Saba', 'XCA', 'AMRO'),
('Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'AFRO'),
('Saint Kitts and Nevis', 'KNA', 'AMRO'),
('Saint Lucia', 'LCA', 'AMRO'),
('Saint Vincent and the Grenadines', 'VCT', 'AMRO'),
('Samoa', 'WSM', 'WPRO'),
('San Marino', 'SMR', 'EURO'),
('Sao Tome and Principe', 'STP', 'AFRO'),
('Saudi Arabia', 'SAU', 'EMRO'),
('Senegal', 'SEN', 'AFRO'),
('Serbia', 'SRB', 'EURO'),
('Seychelles', 'SYC', 'AFRO'),
('Sierra Leone', 'SLE', 'AFRO'),
('Singapore', 'SGP', 'WPRO'),
('Sint Eustatius', 'XBA', 'AMRO'),
('Sint Maarten', 'SXM', 'AMRO'),
('Slovakia', 'SVK', 'EURO'),
('Slovenia', 'SVN', 'EURO'),
('Solomon Islands', 'SLB', 'WPRO'),
('Somalia', 'SOM', 'EMRO'),
('South Africa', 'ZAF', 'AFRO'),
('South Sudan', 'SSD', 'AFRO'),
('Spain', 'ESP', 'EURO'),
('Sri Lanka', 'LKA', 'SEARO'),
('Sudan', 'SDN', 'EMRO'),
('Suriname', 'SUR', 'AMRO'),
('Sweden', 'SWE', 'EURO'),
('Switzerland', 'CHE', 'EURO'),
('Syrian Arab Republic', 'SYR', 'EMRO'),
('Tajikistan', 'TJK', 'EURO'),
('Thailand', 'THA', 'SEARO'),
('The United Kingdom', 'GBR', 'EURO'),
('Timor-Leste', 'TLS', 'SEARO'),
('Togo', 'TGO', 'AFRO'),
('Tokelau', 'TKL', 'WPRO'),
('Tonga', 'TON', 'WPRO'),
('Trinidad and Tobago', 'TTO', 'AMRO'),
('Tunisia', 'TUN', 'EMRO'),
('Turkey', 'TUR', 'EURO'),
('Turkmenistan', 'TKM', 'EURO'),
('Turks and Caicos Islands', 'TCA', 'AMRO'),
('Tuvalu', 'TUV', 'WPRO'),
('Uganda', 'UGA', 'AFRO'),
('Ukraine', 'UKR', 'EURO'),
('United Arab Emirates', 'ARE', 'EMRO'),
('United Republic of Tanzania', 'TZA', 'AFRO'),
('United States of America', 'USA', 'AMRO'),
('Uruguay', 'URY', 'AMRO'),
('Uzbekistan', 'UZB', 'EURO'),
('Vanuatu', 'VUT', 'WPRO'),
('Venezuela (Bolivarian Republic of)', 'VEN', 'AMRO'),
('Viet Nam', 'VNM', 'WPRO'),
('Wallis and Futuna', 'WLF', 'WPRO'),
('Yemen', 'YEM', 'EMRO'),
('Zambia', 'ZMB', 'AFRO'),
('Zimbabwe', 'ZWE', 'AFRO');


#Checking values inserted 
SELECT * FROM country;

##############################################################################################################
-- Creating Data source table
CREATE TABLE data_source (
    source_id   INT (10) AUTO_INCREMENT,
    source_name VARCHAR (10) NOT NULL,
    PRIMARY KEY (source_id)
);

#CHECKING CREATED Data_source table

SELECT * FROM data_source;

INSERT INTO data_source (source_name) VALUES
('REPORTING'), ('REPORTING'), ('REPORTING'), ('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('OWID'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('OWID'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('OWID'),('REPORTING'),('OWID'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('OWID'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('OWID'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('OWID'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),
('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING'),('REPORTING');

SELECT * FROM data_source;
##############################################################################################################
# Vaccine master table
CREATE TABLE vaccine (
    vaccine_id   INT (10) AUTO_INCREMENT,
	date_updated  DATE NOT NULL,
    total_vaccinations BIGINT NOT NULL,
	vaccine_used TEXT NOT NULL,
    PRIMARY KEY (vaccine_id)
);
SELECT * FROM vaccine;

INSERT INTO vaccine (date_updated, total_vaccinations, vaccine_used) VALUES
('2023-04-09', 16625558, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-03-19', 3070468, 'AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-Vac,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2022-09-04', 15267442, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,SII - Covishield,Sinovac - CoronaVac'),
('2023-03-29', 114706, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-02-26', 156957, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-09', 25042414, 'SII - Covishield'),
('2023-04-07', 24604, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 136512, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-10-07', 109652736, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-03-05', 2153341, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac,Wuhan CNBG - Inactivated'),
('2023-04-07', 216812, 'Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty'),
('2023-03-24', 65492360, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 20391629, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Moderna – Spikevax Bivalent Original/Omicron BA.1,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5,Unknown Vaccine,Valneva - VLA2001'),
('2023-03-19', 13812050, 'AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-07', 364701, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-12-21', 3476633, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-11', 358530031, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 381690, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-02-05', 19287182, 'Beijing CNBG - BBIBP-CorV,Chumakov - Covi-Vac,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light'),
('2023-03-19', 29115074, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 510653, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-12-18', 4232541, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 132042, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2022-10-30', 2011426, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 15918685, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 43070, ''),
('2021-09-01', 35845, 'Moderna - mRNA-1273, Pfizer BioNTech - Comirnaty'),
('2022-01-29', 1924950, 'AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty, Sinovac - CoronaVac, Gamaleya - Sputnik V'),
('2023-04-09', 3171667, 'Bharat - Covaxin,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 509399590, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 41453, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty'),
('2023-03-10', 1291223, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 4615074, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 6674010, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2023-04-02', 36281, 'Beijing CNBG - BBIBP-CorV'),
('2022-09-25', 859940, 'Beijing CNBG - BBIBP-CorV,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-03-31', 46808756, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-02', 4548943, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 97224600, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 151661, 'Pfizer BioNTech - Comirnaty'),
('2023-03-26', 2689234, 'Bharat - Covaxin,SII - Covishield'),
('2023-04-02', 8543941, 'Beijing CNBG - BBIBP-CorV'),
('2023-04-07', 65248327, 'AstraZeneca - Vaxzevria,CanSino - Convidecia,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-23', 3515872818, 'Anhui ZL - Zifivax,Beijing CNBG - BBIBP-CorV,CanSino - Convidecia,IMB - Covidful,Pfizer BioNTech - Comirnaty,Shenzhen - LV-SMENP-DC,Sinovac - CoronaVac,Wuhan CNBG - Inactivated'),
('2023-04-07', 90506612, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2022-10-02', 835021, 'Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,SII - Covishield'),
('2022-07-31', 833210, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,SII - Covishield'),
('2023-01-31', 40080, 'Pfizer BioNTech - Comirnaty'),
('2023-04-07', 13066850, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-02-19', 25263932, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-10-23', 5357755, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-04-07', 38047776, 'CIGB - CIGB-66,Finlay - Soberana Plus,Finlay - Soberana-02'),
('2023-04-07', 260324, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 1858220, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-03-05', 18608534, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5'),
('2023-04-02', 15574105, 'SII - Covishield'),
('2023-03-05', 15102608, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-04-09', 391203, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 67647, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 15950237, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-02-24', 39495110, 'AstraZeneca - Vaxzevria,CanSino - Convidecia,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-09', 111558825, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-07', 11379601, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2022-07-24', 488738, 'Beijing CNBG - BBIBP-CorV,Sinovac - CoronaVac'),
('2022-07-03', 0, ''),
('2023-02-26', 2196128, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5'),
('2023-04-09', 847910, 'Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-03-26', 53805400, 'Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2022-06-21', 9390, 'AstraZeneca - AZD1222'),
('2022-02-18', 103894, 'Moderna - mRNA-1273, Pfizer BioNTech - Comirnaty'),
('2023-03-23', 1554370, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,SII - Covishield'),
('2023-03-12', 13249324, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-03-05', 157891260, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5,Unknown Vaccine'),
('2023-04-07', 241789, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-01-31', 471948, 'Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty'),
('2023-02-05', 572672, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 1444492, 'Beijing CNBG - BBIBP-CorV,SII - Covishield'),
('2023-03-12', 2736283, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-05', 193166879, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron  - Generic,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron - Generic,Unknown Vaccine,Valneva - VLA2001'),
('2023-03-26', 22384226, 'Gamaleya - Gam-Covid-Vac,SII - Covishield'),
('2022-12-16', 132810, 'AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty'),
('2023-03-19', 21979563, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5'),
('2022-03-14', 79738, 'Moderna - mRNA-1273'),
('2023-04-07', 90686, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 399511, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-01-31', 352698, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 20324265, 'AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-12-19', 178525, 'Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty'),
('2023-04-02', 10645240, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-02', 600165, 'Beijing CNBG - BBIBP-CorV,SII - Covishield'),
('2023-04-07', 960133, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 608275, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax'),
('2023-04-07', 17268919, 'AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-03-19', 16568528, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Sinovac - CoronaVac'),
('2023-02-26', 868802, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-04-11', 2206624273, 'Bharat - Covaxin,Biological E - Corbevax,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,SII - Covishield,SII - Covovax,Zydus - ZyCov-D'),
('2023-01-17', 444303130, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-02-19', 157785811, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Finlay - Soberana-02,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Shifa - COVIran Barakat,Sinovac - CoronaVac'),
('2023-01-02', 19557364, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-19', 12358591, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2022-06-23', 189994, 'Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty'),
('2022-06-05', 15026951, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-05', 150260818, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5'),
('2023-04-07', 1522173, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-03-30', 383172235, 'AstraZeneca - Vaxzevria,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-01-29', 266953, 'Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty'),
('2022-08-21', 10057975, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-02-19', 33691195, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Pfizer BioNTech - Comirnaty,RIBSP - QazVac,Sinovac - CoronaVac'),
('2023-04-02', 23750431, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-02-06', 219980, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV'),
('2023-01-15', 1836901, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty'),
('2023-04-09', 8259575, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-02-26', 3090060, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,RIBSP - QazVac'),
('2023-01-19', 15053397, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-03-19', 2977413, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5,Unknown Vaccine'),
('2022-12-22', 5814699, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-19', 1339097, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2022-12-11', 4460668, 'SII - Covishield'),
('2023-01-16', 3739158, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2022-04-10', 71104, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-12', 4531267, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-03-19', 1337471, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5'),
('2023-04-09', 2853869, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2023-04-09', 7540975, 'Janssen - Ad26.COV 2-S,SII - Covishield'),
('2023-04-02', 72601123, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-20', 951645, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-09', 5761850, 'SII - Covishield'),
('2023-03-05', 1280049, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-24', 110742, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 401431, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty'),
('2023-04-02', 4068530, 'Beijing CNBG - BBIBP-CorV,SII - Covishield'),
('2023-04-09', 2614763, 'Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,SII - Covishield'),
('2023-04-07', 222580922, 'AstraZeneca - Vaxzevria,CanSino - Convidecia,CIGB - CIGB-66,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-28', 198749, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2022-12-04', 71027, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax - Covavax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-03-17', 5668144, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-12-04', 523735, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-04-07', 4619, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty'),
('2023-04-04', 55387241, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-09', 29457535, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2022-06-18', 64549994, 'Beijing CNBG - BBIBP-CorV,SII - Covishield'),
('2023-04-09', 988027, 'Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-02-20', 32157, 'AstraZeneca - Vaxzevria,SII - Covishield'),
('2023-04-11', 61476637, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2022-09-11', 36105753, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Unknown Vaccine'),
('2023-04-03', 480497, 'Janssen - Ad26.COV 2-S,Pfizer BioNTech - Comirnaty'),
('2023-03-31', 11999352, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 15304013, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,CIGB - CIGB-66,Finlay - Soberana Plus,Finlay - Soberana-02,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-03-12', 7339299, 'Beijing CNBG - BBIBP-CorV,SII - Covishield'),
('2023-03-19', 116606863, 'SII - Covishield'),
('2023-03-04', 4923, 'Pfizer BioNTech - Comirnaty'),
('2023-01-08', 1862732, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac,Wuhan CNBG - Inactivated'),
('2022-11-04', 116159, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 12318248, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2022-10-18', 3748571, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2022-10-25', 7086050, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-02', 334981904, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-03-10', 51032, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-07', 8866774, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-02', 521130, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2-S,SII - Covishield'),
('2023-04-07', 9623482, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Gamaleya - Gam-Covid-Vac,Julphar - Hayat-Vax,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-04-07', 88628251, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-03-09', 170690206, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Julphar - Hayat-Vax,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2022-02-28', 138, 'AstraZeneca - Vaxzevria'),
('2023-03-12', 58085517, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-03-12', 27741176, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Janssen - Ad26.COV 2-S,Moderna – Spikevax Bivalent Original/Omicron BA.1,Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1,Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5,Sinovac - CoronaVac'),
('2023-04-07', 7834186, 'Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-04-09', 7608683, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,CanSino - Convidecia,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-30', 135716807, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Novavax-NUVAXOVID,Pfizer BioNTech - Comirnaty'),
('2023-03-19', 2284353, 'AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,Sinovac - CoronaVac'),
('2023-03-19', 16108109, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty'),
('2023-04-03', 186318525, 'SRCVB - EpiVacCorona, Gamaleya - Sputnik V'),
('2023-01-01', 26106436, 'Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid-Vac,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield,Sinovac - CoronaVac'),
('2023-04-07', 4979, ''),
('2021-05-05', 7892, 'AstraZeneca - AZD1222'),
('2023-04-07', 64297, 'AstraZeneca - Vaxzevria,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 122977, 'AstraZeneca - Vaxzevria,Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfizer BioNTech - Comirnaty,SII - Covishield'),
('2023-04-07', 73435, 'AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-Vac,Gamaleya - Sputnik-Light,Pfizer BioNTech - Comirnaty,SII - Covishield');
##############################################################################################################
#Checking Vaccine Data
SELECT * FROM vaccine;

CREATE TABLE vaccination_snapshot (
    snapshot_id        INT AUTO_INCREMENT PRIMARY KEY,
    country_id         INT NOT NULL,
    source_id          INT NOT NULL,
    vaccine_id         INT NOT NULL,
    date_updated       DATE NOT NULL,
    total_vaccinations INT,

    CONSTRAINT fk_snapshot_country FOREIGN KEY (country_id) REFERENCES country(country_id),
    CONSTRAINT fk_snapshot_source FOREIGN KEY (source_id) REFERENCES data_source(source_id),
    CONSTRAINT fk_snapshot_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccine(vaccine_id)
);
################################################################################################################
# QUESTION 1 -Top 10 vaccines used (text search inside vaccine_used)

SELECT vaccine_used,
       COUNT(*) AS times_used
FROM vaccine
GROUP BY vaccine_used
ORDER BY times_used DESC
LIMIT 15;



# QUESTION 2Total vaccinations per year
SELECT YEAR(date_updated) AS year,
       SUM(total_vaccinations) AS yearly_total
FROM vaccine
GROUP BY YEAR(date_updated)
ORDER BY year;

#. Find all reports where vaccine_used IS NULL or empty
SELECT vaccine_id, date_updated, total_vaccinations
FROM vaccine
WHERE vaccine_used IS NULL OR vaccine_used = '';

#Get the minimum, maximum, and average vaccination count for 2022
SELECT MIN(total_vaccinations) AS min_2022,
       MAX(total_vaccinations) AS max_2022,
       AVG(total_vaccinations) AS avg_2022
FROM vaccine
WHERE YEAR(date_updated) = 2022;
